ctrl_interface=/var/run/wpa_supplicant
ap_scan=1
country=US

network={
    ssid="Tmobile-BD21"
    psk="proximity.freedom.crunching.gathering"
    priority=5
}

network={
    ssid="BackupWiFi"
    psk="backup_pass"
    priority=1
}

